version: "3.1"

services:
  db:
    container_name: ${POSTGRES_DOCKER_CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.docker/.volumes/postgres/:/var/lib/postgresql
